#pragma once

enum {
    ITEM_EFFECT_MOVE,
    ITEM_EFFECT_HEAL,
    ITEM_EFFECT_PASSIVE,
    ITEM_EFFECT_ESCAPE,
    ITEM_EFFECT_COUNT
};

enum {
    ITEM_NONE,
    ITEM_THROWING_KNIFE,
    ITEM_BOMB,
    ITEM_POTION,
    ITEM_EARTH_SCROLL,
    ITEM_WATER_SCROLL,
    ITEM_AIR_SCROLL,
    ITEM_FIRE_SCROLL,
    ITEM_DRAGON_SCALE,
    ITEM_ESCAPE_SCROLL,
    ITEM_COUNT
};