#pragma once

enum {
    MONSTER_NONE,
    MONSTER_WOLF,
    MONSTER_BAT,
    MONSTER_EARTH_MAGE,
    MONSTER_AIR_MAGE,
    MONSTER_WATER_MAGE,
    MONSTER_FIRE_MAGE,
    MONSTER_DRAGON,
    MONSER_COUNT
};