#pragma once

enum {
    MONSTER_NONE,
    MONSTER_WOLF,
    MONSTER_BAT,
    MONSTER_WIZARD_E,
    MONSTER_WIZARD_A,
    MONSTER_WIZARD_W,
    MONSTER_WIZARD_F,
    MONSTER_DRAGON,
    MONSER_COUNT
};