#pragma once

#define ELEMENT_EARTH (1 << 0)
#define ELEMENT_WATER (1 << 1)
#define ELEMENT_AIR (1 << 2)
#define ELEMENT_FIRE (1 << 3)

enum {
    EFFECT_HIT,
    EFFECT_HEAL,
    MOVE_EFFECT_COUNT
};

enum {
    MOVE_NONE,
    MOVE_BITE,
    MOVE_THROWING_KNIFE,
    MOVE_BOMB,
    MOVE_EARTH_SPELL,
    MOVE_WATER_SPELL,
    MOVE_AIR_SPELL,
    MOVE_FIRE_SPELL,
    MOVE_DRAGON_FIRE,
    MOVE_HEAL,
    MOVE_COUNT
};