#pragma once

enum {
    TEX_WOLF,
    TEX_BAT,
    TEX_EARTH_MAGE,
    TEX_AIR_MAGE,
    TEX_WATER_MAGE,
    TEX_FIRE_MAGE,
    TEX_DRAGON,
    TEX_DUNGEON_TILESET,
    TEX_PLAYER,
    TEX_CURSOR,
    TEX_BACKGROUND,
    TEX_THROW_KNIFE_MOVE,
    TEX_BOMB_MOVE,
    TEX_AIR_SPELL_MOVE,
    TEX_EARTH_SPELL_MOVE,
    TEX_FIRE_SPELL_MOVE,
    TEX_WATER_SPELL_MOVE,
    TEX_COUNT
};