#pragma once

enum {
    TEX_WOLF,
    TEX_BAT,
    TEX_EARTH_MAGE,
    TEX_AIR_MAGE,
    TEX_WATER_MAGE,
    TEX_FIRE_MAGE,
    TEX_DRAGON,
    TEX_DUNGEON_TILESET,
    TEX_PLAYER,
    TEX_CURSOR,
    TEX_BACKGROUND,
    TEX_COUNT
};